### ISSUE TITLE
Make it work for execution path - not script location path. 

### ISSUE THREAD

**Issue by kimusan** [trustedsec/spoonmap#3]
It would be nice if it was possible to actually place the script in path and execute it from everywhere. Right now it does everything relative to script location so if I install in e.g. /usr/bin then it wants to create folders etc in that folder. 
Change it to put the folders relative to where it is executed from or make it a question in the menu.

**Comment by Spoonman1091** [comment]
Just merged a couple of pull requests that should address this issue.
